PROJ_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Configuration of extension
EXTENSION_NAME=SAYHELLO
EXTENSION_VERSION=v1.0.0
EXT_FLAGS=\
-DDUCKDB_EXTENSION_NAMES="sayhello" \
-DDUCKDB_EXTENSION_${EXTENSION_NAME}_PATH="$(PROJ_DIR)" \
-DDUCKDB_EXTENSION_${EXTENSION_NAME}_SHOULD_LINK=0 \
-DDUCKDB_EXTENSION_${EXTENSION_NAME}_LOAD_TESTS=1 \
-DDUCKDB_EXTENSION_${EXTENSION_NAME}_TEST_PATH="$(PROJ_DIR)test/sql" \
-DDUCKDB_EXTENSION_${EXTENSION_NAME}_EXT_VERSION="$(EXTENSION_VERSION)"

EXT_CONFIG=${PROJ_DIR}extension_config.cmake

# Include the Makefile from extension-ci-tools
include makefiles/duckdb_extension.Makefile
